// src/components/PlayerScoreRow.vue
<template>
  <div class="list-row player-row" :class="{ absent: isOut }">
    <div class="icon-box sm player-avatar" :class="{ champ: isChamp }">
      {{ player.isFill ? '∅' : initials(player.name) }}
    </div>
    <div class="player-info">
      <div class="player-name">
        <template v-if="player.isFill">
          <span style="color:var(--muted);font-style:italic;">League Avg Fill</span>
        </template>
        <template v-else>
          {{ player.name
          }}<span v-if="isChamp" class="champ-crown">👑</span
          ><span v-if="isOut" class="absent-tag">OUT</span
          ><span v-if="player.isFill" class="fill-tag">FILL</span>
        </template>
      </div>
      <div v-if="playerAvg > 0 && !player.isFill" class="subtext">avg {{ playerAvg.toFixed(1) }}</div>
      <div v-else-if="player.isFill" class="subtext">fill</div>
    </div>
    <div class="score-inputs">
      <div class="score-group">
        <span class="label-sm">G{{ gameNum }}</span>
        <!-- Fill slot: read-only league avg display -->
        <div v-if="player.isFill" class="score-display" style="color:var(--muted);">
          {{ Math.round(leagueAvg) }}
        </div>
        <!-- Expected mode: computed avg read-only -->
        <div v-else-if="mode === 'expected'" class="score-display" style="color:var(--muted);">
          {{ expectedScore }}
        </div>
        <!-- Scores mode: editable input -->
        <input
          v-else
          type="number"
          inputmode="numeric"
          pattern="[0-9]*"
          :class="{
            'has-score': hasValue,
            'score-pending': isPending,
            'absent-prefill': isAbsentPrefill,
          }"
          placeholder="—"
          :value="displayValue"
          @input="onInput"
          :title="isAbsentPrefill ? 'Pre-filled league avg (player is Out). Type real score to override.' : ''"
        >
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useDataStore }    from '../stores/data.js'
import { usePendingStore } from '../stores/pending.js'
import { usePrefsStore }   from '../stores/prefs.js'
import { initials }        from '../utils/helpers.js'
import { isChampion, isPlayerOut, getPlayerCurrentAvg, effectiveAvg } from '../utils/data.js'

const props = defineProps({
  /** Active-week player: { name, slot, g1, g2, g3, isFill } */
  player:   { type: Object, required: true },
  teamName: { type: String, required: true },
  gameNum:  { type: Number, required: true },
  mode:     { type: String, default: 'scores' }, // 'scores' | 'expected'
  leagueAvg: { type: Number, default: 0 },
})

const dataStore    = useDataStore()
const pendingStore = usePendingStore()
const prefsStore   = usePrefsStore()

const isChamp = computed(() => isChampion(dataStore.champions, props.player.name))
const isOut   = computed(() => !props.player.isFill && isPlayerOut(dataStore.rsvp, props.player.name))

const playerAvg = computed(() =>
  props.player.isFill
    ? props.leagueAvg
    : getPlayerCurrentAvg(dataStore.stats, dataStore.settings, props.player.name, prefsStore.avgDisplay)
)

const expectedScore = computed(() => {
  const avg = effectiveAvg(
    dataStore.stats, dataStore.settings, dataStore.rsvp,
    props.player.name, props.player.isFill, props.leagueAvg
  )
  return avg > 0 ? Math.round(avg) : '—'
})

// Raw score from the active-week sheet for this game
const rawScore = computed(() => {
  if (props.gameNum === 1) return props.player.g1
  if (props.gameNum === 2) return props.player.g2
  return props.player.g3
})

const pendingKey   = computed(() => `${props.teamName}|${props.player.slot}|${props.gameNum}`)
const pendingEntry = computed(() => pendingStore.pendingScores[pendingKey.value])

// Value shown in the input (pending takes priority over stored)
const displayValue = computed(() => {
  if (pendingEntry.value) return pendingEntry.value.score
  return rawScore.value === '' || rawScore.value == null ? '' : rawScore.value
})

const hasValue      = computed(() => displayValue.value !== '' && displayValue.value != null)
const isPending     = computed(() => !!pendingEntry.value)
// Absent player whose field already has a league-avg prefill from the backend
const isAbsentPrefill = computed(() =>
  isOut.value && rawScore.value !== '' && rawScore.value != null
)

function onInput(e) {
  const val     = e.target.value
  const initial = rawScore.value === '' || rawScore.value == null ? '' : String(rawScore.value)
  if (val !== initial && val !== '') {
    pendingStore.pendingScores = {
      ...pendingStore.pendingScores,
      [pendingKey.value]: {
        team:    props.teamName,
        slot:    props.player.slot,
        gameNum: props.gameNum,
        score:   val,
      },
    }
  } else {
    const next = { ...pendingStore.pendingScores }
    delete next[pendingKey.value]
    pendingStore.pendingScores = next
  }
}
</script>

// app/src/components/PlayerScoreRow.tsx
import React from 'react'
import { View, Text, TextInput, StyleSheet } from 'react-native'
import { useDataStore } from '../stores/dataStore'
import { usePendingStore } from '../stores/pendingStore'
import { usePrefsStore } from '../stores/prefsStore'
import { initials } from '../utils/helpers.js'
import { isChampion, isPlayerOut, getPlayerCurrentAvg, effectiveAvg } from '../utils/data.js'
import { colors, fonts, radius } from '../theme'

interface PlayerScoreRowProps {
  player: { name: string; slot: number; g1: any; g2: any; g3: any; isFill?: boolean }
  teamName: string
  gameNum: number
  mode: 'scores' | 'expected'
  leagueAvg: number
}

export default function PlayerScoreRow({ player, teamName, gameNum, mode, leagueAvg }: PlayerScoreRowProps) {
  const { champions, rsvp, stats, settings } = useDataStore()
  const { pendingScores, set } = usePendingStore()
  const { avgDisplay } = usePrefsStore()

  const isChamp = isChampion(champions, player.name)
  const isOut = !player.isFill && isPlayerOut(rsvp, player.name)

  const playerAvg = player.isFill
    ? leagueAvg
    : getPlayerCurrentAvg(stats, settings, player.name, avgDisplay as any)

  const expectedScore = (() => {
    const avg = effectiveAvg(stats, settings, rsvp, player.name, !!player.isFill, leagueAvg)
    return avg > 0 ? Math.round(avg) : '—'
  })()

  const rawScore = gameNum === 1 ? player.g1 : gameNum === 2 ? player.g2 : player.g3
  const pendingKey = `${teamName}|${player.slot}|${gameNum}`
  const pendingEntry = pendingScores[pendingKey]

  const displayValue = pendingEntry
    ? String(pendingEntry)
    : rawScore === '' || rawScore == null
    ? ''
    : String(rawScore)

  const hasValue = displayValue !== '' && displayValue != null
  const isPending = !!pendingEntry
  const isAbsentPrefill = isOut && rawScore !== '' && rawScore != null

  function onChangeText(val: string) {
    const initial = rawScore === '' || rawScore == null ? '' : String(rawScore)
    if (val !== initial && val !== '') {
      set({ pendingScores: { ...pendingScores, [pendingKey]: val } })
    } else {
      const next = { ...pendingScores }
      delete next[pendingKey]
      set({ pendingScores: next })
    }
  }

  return (
    <View style={[styles.row, isOut && styles.rowAbsent]}>
      <View style={[styles.avatar, isChamp && styles.avatarChamp]}>
        <Text style={styles.avatarText}>{player.isFill ? '∅' : initials(player.name)}</Text>
      </View>
      <View style={{ flex: 1 }}>
        {player.isFill ? (
          <Text style={[styles.playerName, { color: colors.muted, fontStyle: 'italic' }]}>League Avg Fill</Text>
        ) : (
          <Text style={styles.playerName}>
            {player.name}
            {isChamp ? ' 👑' : ''}
            {isOut ? <Text style={styles.outTag}> OUT</Text> : null}
          </Text>
        )}
        {playerAvg > 0 && !player.isFill ? (
          <Text style={styles.subtext}>avg {playerAvg.toFixed(1)}</Text>
        ) : player.isFill ? (
          <Text style={styles.subtext}>fill</Text>
        ) : null}
      </View>
      <View style={styles.scoreGroup}>
        <Text style={styles.gameLabel}>G{gameNum}</Text>
        {player.isFill ? (
          <Text style={styles.scoreDisplay}>{Math.round(leagueAvg)}</Text>
        ) : mode === 'expected' ? (
          <Text style={[styles.scoreDisplay, { color: colors.muted }]}>{expectedScore}</Text>
        ) : (
          <TextInput
            style={[
              styles.scoreInput,
              hasValue && styles.scoreInputHasValue,
              isPending && styles.scoreInputPending,
              isAbsentPrefill && styles.scoreInputAbsent,
            ]}
            keyboardType="number-pad"
            placeholder="—"
            placeholderTextColor={colors.muted2}
            value={displayValue}
            onChangeText={onChangeText}
          />
        )}
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  rowAbsent: {
    opacity: 0.5,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: radius.icon,
    backgroundColor: colors.surface3,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  avatarChamp: {
    borderWidth: 1,
    borderColor: colors.gold,
  },
  avatarText: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 12,
    color: colors.text,
    letterSpacing: 0.5,
  },
  playerName: {
    fontFamily: fonts.barlow,
    fontSize: 14,
    color: colors.text,
  },
  outTag: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 10,
    color: colors.danger,
    letterSpacing: 1,
  },
  subtext: {
    fontFamily: fonts.barlow,
    fontSize: 11,
    color: colors.muted,
    marginTop: 1,
  },
  scoreGroup: {
    alignItems: 'flex-end',
    minWidth: 56,
  },
  gameLabel: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 10,
    color: colors.muted,
    letterSpacing: 1,
    marginBottom: 2,
  },
  scoreDisplay: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 20,
    color: colors.text,
    minWidth: 40,
    textAlign: 'right',
  },
  scoreInput: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 20,
    color: colors.muted,
    borderBottomWidth: 1,
    borderBottomColor: colors.border2,
    minWidth: 40,
    textAlign: 'right',
    paddingVertical: 0,
    paddingHorizontal: 4,
  },
  scoreInputHasValue: {
    color: colors.text,
  },
  scoreInputPending: {
    color: colors.accent,
    borderBottomColor: colors.accent,
  },
  scoreInputAbsent: {
    color: colors.muted,
    borderBottomColor: colors.border,
  },
})
