// app/src/components/OddsBlock.tsx
import React from 'react'
import { View, Text, StyleSheet } from 'react-native'
import { spreadAndML } from '../utils/helpers.js'
import { colors, fonts, radius } from '../theme'

interface TeamForOdds {
  name: string
  players: { name: string; isFill?: boolean; effectiveAvg?: number }[]
}

interface OddsBlockProps {
  teamA: TeamForOdds
  teamB: TeamForOdds
  leagueAvg: number
  label: string
}

export default function OddsBlock({ teamA, teamB, leagueAvg, label }: OddsBlockProps) {
  const expectedA = teamA.players.reduce((s, p) => {
    const avg = p.effectiveAvg ?? leagueAvg
    return s + (avg > 0 ? Math.round(avg) : 0)
  }, 0)

  const expectedB = teamB.players.reduce((s, p) => {
    const avg = p.effectiveAvg ?? leagueAvg
    return s + (avg > 0 ? Math.round(avg) : 0)
  }, 0)

  const odds = spreadAndML(expectedA, expectedB)
  const teamAIsFav = odds.fav === 't1'

  const favName = odds.fav === 't1' ? teamA.name : odds.fav === 't2' ? teamB.name : ''
  const dogName = odds.fav === 't1' ? teamB.name : odds.fav === 't2' ? teamA.name : ''

  const teamARoster = teamA.players.map(p => (p.isFill ? 'Fill' : p.name)).join(' · ') || '—'
  const teamBRoster = teamB.players.map(p => (p.isFill ? 'Fill' : p.name)).join(' · ') || '—'

  return (
    <View style={styles.block}>
      {odds.fav === 'tie' ? (
        <>
          <View style={styles.head}>
            <Text style={styles.label}>{label}</Text>
            <Text style={styles.pickem}>PICK 'EM ({expectedA})</Text>
          </View>
          <View style={styles.teams}>
            <View style={styles.teamSide}>
              <Text style={styles.teamName}>{teamA.name}<Text style={styles.proj}> {expectedA}</Text></Text>
              <Text style={styles.roster}>{teamARoster}</Text>
            </View>
            <View style={styles.teamSide}>
              <Text style={styles.teamName}>{teamB.name}<Text style={styles.proj}> {expectedB}</Text></Text>
              <Text style={styles.roster}>{teamBRoster}</Text>
            </View>
          </View>
        </>
      ) : (
        <>
          <View style={styles.head}>
            <Text style={styles.label}>{label}</Text>
            <View style={styles.lineStack}>
              <View style={styles.lineRow}>
                <Text style={styles.prefix}>SPREAD</Text>
                <View style={styles.chipFav}><Text style={styles.chipFavText}>{favName} -{odds.spread}</Text></View>
              </View>
              <View style={styles.lineRow}>
                <Text style={styles.prefix}>ML</Text>
                <View style={styles.chipFav}><Text style={styles.chipFavText}>{favName} {odds.ml?.fav}</Text></View>
                <View style={styles.chipDog}><Text style={styles.chipDogText}>{dogName} {odds.ml?.dog}</Text></View>
              </View>
            </View>
          </View>
          <View style={styles.teams}>
            <View style={[styles.teamSide, teamAIsFav && styles.teamFav]}>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                <Text style={styles.teamName}>{teamA.name}</Text>
                {teamAIsFav && <View style={styles.favTag}><Text style={styles.favTagText}>FAV</Text></View>}
                <Text style={styles.proj}>{expectedA}</Text>
              </View>
              <Text style={styles.roster}>{teamARoster}</Text>
            </View>
            <View style={[styles.teamSide, !teamAIsFav && styles.teamFav]}>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                <Text style={styles.teamName}>{teamB.name}</Text>
                {!teamAIsFav && <View style={styles.favTag}><Text style={styles.favTagText}>FAV</Text></View>}
                <Text style={styles.proj}>{expectedB}</Text>
              </View>
              <Text style={styles.roster}>{teamBRoster}</Text>
            </View>
          </View>
        </>
      )}
    </View>
  )
}

const styles = StyleSheet.create({
  block: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  head: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  label: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: colors.muted,
    flex: 1,
    marginRight: 8,
  },
  pickem: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 13,
    fontWeight: '700',
    color: colors.accent,
    letterSpacing: 1,
  },
  lineStack: { alignItems: 'flex-end', gap: 4 },
  lineRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  prefix: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 10,
    letterSpacing: 1,
    color: colors.muted,
  },
  chipFav: {
    backgroundColor: 'rgba(232,255,71,0.12)',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  chipFavText: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 12,
    color: colors.accent,
    letterSpacing: 0.5,
  },
  chipDog: {
    backgroundColor: colors.surface3,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  chipDogText: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 12,
    color: colors.muted,
    letterSpacing: 0.5,
  },
  teams: { flexDirection: 'row', gap: 8 },
  teamSide: { flex: 1 },
  teamFav: {},
  teamName: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 13,
    color: colors.text,
    fontWeight: '700',
  },
  proj: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 13,
    color: colors.muted,
  },
  roster: {
    fontFamily: fonts.barlow,
    fontSize: 11,
    color: colors.muted,
    marginTop: 2,
  },
  favTag: {
    backgroundColor: 'rgba(232,255,71,0.12)',
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  favTagText: {
    fontFamily: fonts.barlowCondensed,
    fontSize: 10,
    color: colors.accent,
    letterSpacing: 1,
  },
})

// src/components/OddsBlock.vue
<template>
  <div class="odds-block">
    <!-- Pick-em -->
    <template v-if="odds.fav === 'tie'">
      <div class="odds-block-head">
        <span class="label">{{ label }}</span>
        <span class="odds-block-pickem">PICK 'EM ({{ expectedA }})</span>
      </div>
      <div class="odds-block-teams">
        <div class="odds-team-side">
          <div class="odds-team-name">{{ teamA.name }}<span class="odds-team-proj">{{ expectedA }}</span></div>
          <div class="odds-roster">{{ teamARoster }}</div>
        </div>
        <div class="odds-team-side">
          <div class="odds-team-name">{{ teamB.name }}<span class="odds-team-proj">{{ expectedB }}</span></div>
          <div class="odds-roster">{{ teamBRoster }}</div>
        </div>
      </div>
    </template>

    <!-- Normal line -->
    <template v-else>
      <div class="odds-block-head">
        <span class="label">{{ label }}</span>
        <div class="odds-line-stack">
          <div class="odds-line-row">
            <span class="odds-prefix">SPREAD</span>
            <span class="odds-chip fav">{{ favName }} -{{ odds.spread }}</span>
          </div>
          <div class="odds-line-row">
            <span class="odds-prefix">ML</span>
            <span class="odds-chip fav">{{ favName }} {{ odds.ml.fav }}</span>
            <span class="odds-chip dog">{{ dogName }} {{ odds.ml.dog }}</span>
          </div>
        </div>
      </div>
      <div class="odds-block-teams">
        <div class="odds-team-side" :class="teamAIsFav ? 'fav' : 'dog'">
          <div class="odds-team-name">
            {{ teamA.name }}
            <span v-if="teamAIsFav" class="odds-tag-fav">FAV</span>
            <span class="odds-team-proj">{{ expectedA }}</span>
          </div>
          <div class="odds-roster">{{ teamARoster }}</div>
        </div>
        <div class="odds-team-side" :class="teamAIsFav ? 'dog' : 'fav'">
          <div class="odds-team-name">
            {{ teamB.name }}
            <span v-if="!teamAIsFav" class="odds-tag-fav">FAV</span>
            <span class="odds-team-proj">{{ expectedB }}</span>
          </div>
          <div class="odds-roster">{{ teamBRoster }}</div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useDataStore } from '../stores/data.js'
import { effectiveAvg } from '../utils/data.js'
import { spreadAndML }  from '../utils/helpers.js'

const props = defineProps({
  /** Team objects: { name: string, players: { name, isFill, ... }[] } */
  teamA:    { type: Object, required: true },
  teamB:    { type: Object, required: true },
  leagueAvg: { type: Number, default: 0 },
  label:    { type: String, default: '' },
})

const dataStore = useDataStore()

const expectedA = computed(() =>
  props.teamA.players.reduce((s, p) => {
    const avg = effectiveAvg(
      dataStore.stats, dataStore.settings, dataStore.rsvp,
      p.name, p.isFill, props.leagueAvg
    )
    return s + (avg > 0 ? Math.round(avg) : 0)
  }, 0)
)

const expectedB = computed(() =>
  props.teamB.players.reduce((s, p) => {
    const avg = effectiveAvg(
      dataStore.stats, dataStore.settings, dataStore.rsvp,
      p.name, p.isFill, props.leagueAvg
    )
    return s + (avg > 0 ? Math.round(avg) : 0)
  }, 0)
)

const odds      = computed(() => spreadAndML(expectedA.value, expectedB.value))
const teamAIsFav = computed(() => odds.value.fav === 't1')

const favName = computed(() =>
  odds.value.fav === 't1' ? props.teamA.name :
  odds.value.fav === 't2' ? props.teamB.name : ''
)
const dogName = computed(() =>
  odds.value.fav === 't1' ? props.teamB.name :
  odds.value.fav === 't2' ? props.teamA.name : ''
)

const teamARoster = computed(() =>
  props.teamA.players.map(p => p.isFill ? 'Fill' : p.name).join(' · ') || '—'
)
const teamBRoster = computed(() =>
  props.teamB.players.map(p => p.isFill ? 'Fill' : p.name).join(' · ') || '—'
)
</script>
